ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQFx2Vd1U8lIILF2QjwVqfHjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzExMTU0ODE0WhcNMzQw
  MzA5MTU0ODE0WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTQfyhhBXHTlQNJgpfsgcjyoRcFDvmQyn1
  53c6+e+XOAxl3bxwluOoMD25FHEWYd4XIGJCbhWOe4jZnYGA7j93+v1r+tsGFNOL
  78tHfwX/iyzuek5Ji1FDdHiu+OqmjATsHcBXq3rLwWtRmckvDh9iLxZqKsZZQq6r
  mf+qQA0oGYgItoGpTJq9MbnrDf0xChZ6tITkBQmzf0vDhGfKKHWadh6VBVN+IMQL
  iUnAIGvQgzELiUbvN4oPlgEbdyaWlnbR+3gddoNF63GkE31L4GLkYvR6xltO6Af4
  6ec7001+OPQdeCXGs9db1AkV88+6h2/lTFpvllb1kaoP7gL2XIHTAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRrc6bfOPsRtPDktLmJ+QBuFtDG
  xjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAXSEyKPF936brxSBjOBGjtu7CRL6jMEGs9x+t/brS0L6/
  Q1+auSufw91U5wqGj3sG5HQmeL8Sotfv+4g/ZhH8ZXCAUSEGL5IL/kzTv6yMhb6a
  57J0sex8shoeBiyvNXcBLolv88GPPi9FgX+uzKBl+RFqeLt7Sr+6F16qttfZh0Qn
  71n5hYg2r5/B1gbqbhPJcoWYs5dyiEpTkmqZ+3HIrIpHQDcItiKpnVfh8Caxe2m6
  D+gOhFp0WFVCANwPaPHyuepfG9eoYZVbL2ho+PldZnohgCH4kLmX1mdUr1N/IT0i
  bnj0bCII1eGETpNSHqh8LuH4cJeFVGpKWgbsqGv5+g==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQXgee/j4OX3NVMWeAXGnE/TANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzExMTU0OTQ2WhcNMjUw
  MzExMTU0OTQ2WjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmHo0z0y96V2jnAfg
  oXsWfN7WWLDPUMFQgqScN6eFkvTehJTUA0piEoH0QumNaXzgzCHJUCeoaNTuqn28
  2BbyWBsFSXKM4A9IHxqNhmIsEWT2HSOHXvHSwr0LdPlZolPTxUmMRHU11NejrqMo
  5nUwfgIYre31scQl31C+9vpiPYlD+oahrbYf5h/YGl/Ywed6H95RrMMXdBoYSvEB
  zrSsPpYFjN59gHLqExvWF06WPifQ6B2gXQNnLRlz70JMZhu4qrBYR7yhtbrIln58
  Jc/TUSfbVbKgiqTyA11VuZ+CLiRPeXYG+COlWhAMC6ttsHJt4PJxa87qEXAsJCV5
  Zobn4wIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUa3Om3zj7EbTw
  5LS5ifkAbhbQxsYwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  AB7DmHtGzxaj+z+ZJhqZwZ3FweORRt3Da7iKH1f0NpMXDdNN6Cms8F7zs1xJ3wt3
  Y8uPN+K3RLv1z7+1zKP1TaYW6aLw0dcoQhJ6leC+PT4dFlT8wGgII5uEBA67/PAt
  9r7azmTA1RY3Cve+frJErWxSvCsltaY2M/PvkTs689ctmBJm44MKIhUrCooUB4iz
  2ZGZT1LtH8qrL/SI0V2lHCdfVRUGbsGE8fCXUkLuraYqwrGmwjPTpXCbxEih/TSQ
  At26RBTOFDDf24jbwuts/ys1RklDboMOi+opAC9MbDCZY66ozDtIHRo/CjQZSma3
  2U6xOEoAWCEJ3lHA/zD4rP4=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEoAIBAAKCAQEAmHo0z0y96V2jnAfgoXsWfN7WWLDPUMFQgqScN6eFkvTehJTU
  A0piEoH0QumNaXzgzCHJUCeoaNTuqn282BbyWBsFSXKM4A9IHxqNhmIsEWT2HSOH
  XvHSwr0LdPlZolPTxUmMRHU11NejrqMo5nUwfgIYre31scQl31C+9vpiPYlD+oah
  rbYf5h/YGl/Ywed6H95RrMMXdBoYSvEBzrSsPpYFjN59gHLqExvWF06WPifQ6B2g
  XQNnLRlz70JMZhu4qrBYR7yhtbrIln58Jc/TUSfbVbKgiqTyA11VuZ+CLiRPeXYG
  +COlWhAMC6ttsHJt4PJxa87qEXAsJCV5Zobn4wIDAQABAoIBACmgk3JU3TQs4FHk
  xKrRU95bZ+Fmw/KkFDrWfd+j2I+6UlWX3BnZ4NR0rh7mbDj0YtrYDoHXkd6s40ug
  cEH+YcMz/UmEAHnbMjFrql+ZxbYp/hcOcBK3qnaH7ezNdm8eu54M6kJ2TXACPyma
  WbwxGkAMinhRktYpWr2Q6dG7ob5yoz3I9I1CXxQY0cbZ1zMP3U1pHaId6qMVwAvs
  +3SBuywvlhqjdqQ42fw/YB3ta3UkAN1jlGc/uKlT0lCY9XXePaF+69bRQhHZgJ/C
  1jFHaZqxk0ZUqgvN6SCe2k2vZ2K/UfP10uqZ/iolqI7Vb+Obsk/ofsRmHTGrb/Di
  xRcm4uECgYEAwzuIjE1RW41uH5ZkG5IH8qo1EbtHMrHQrvCnrUOfRiAIKAEmlFaL
  20MWQpn+CIerlGgt0HOU7+xrcat+etGlkSgia5STQFmWds9kPgvIOLtFdq/pLBqy
  qljzTKauuKL7aliszlZYOUkQQgORDeGpyAG7CZEbCp3QBcLB8o21APUCgYEAx+/d
  tr1pVzn2QhtPnLkv0iEm1MIaIUveHQm+85IMiFEbp3yWLsM8MBsl9uIizh6n4Dit
  HGQUGOs5mn8gDDPbk71wQloJCAh5chiNQGOqKNW1x/Jr/Tc61k8+U0vrZGIkiQ03
  PNxx17fkG3dVg3LRQzWKLrlEMJwxuc5gowjz3ncCgYBUxPy9LrUss3Qlcv90mSuq
  Sg1Q7ag0ctDRpNypdrspj67678T4k7uWMMLxmDudKItvnOyHnigFJPpiGLyKR41E
  QdDwNUrangue+t3jsun0+BtpNWhhJhZ9sLGzjow+z0WrH2WpEgSsmvTcNQA+rsUx
  es7jkIXVTkCMv8vGrZDyIQKBgB38Xo86pyLa4ZEWkYEa0Q49xJoiJlMaEszeGlJj
  dBe5umELMWcABvXcDHyTe87YECtztJrOc6ktFi2SpVbPLD5jKgP5huM6iiRPhFfE
  2s9XBfVf6UxHzT45Ekrh1wLuKTaY0dEB6t0EimSIKD4XqUTgMcJCLPTxaA/K4Ply
  rUiPAn8cvU3Ibu/esSFC70pbwM7QK5wUpTYplH+pdHp6DGC2Y9Q5/RiXPM8PpM/Q
  mfy3j54t01DjYis64HCRsXW/Hd5m3OJlwT0VjtjRRagtPYlgZLYNgvVnblanjlxE
  eMffLeGeAQD6pnAH2W9ENxTZBn7JemZ6uniwXGfJMHE0Cs+Q
  -----END RSA PRIVATE KEY-----
api_connection_string: localhost:8001
name: admin
