ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQFx2Vd1U8lIILF2QjwVqfHjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzExMTU0ODE0WhcNMzQw
  MzA5MTU0ODE0WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTQfyhhBXHTlQNJgpfsgcjyoRcFDvmQyn1
  53c6+e+XOAxl3bxwluOoMD25FHEWYd4XIGJCbhWOe4jZnYGA7j93+v1r+tsGFNOL
  78tHfwX/iyzuek5Ji1FDdHiu+OqmjATsHcBXq3rLwWtRmckvDh9iLxZqKsZZQq6r
  mf+qQA0oGYgItoGpTJq9MbnrDf0xChZ6tITkBQmzf0vDhGfKKHWadh6VBVN+IMQL
  iUnAIGvQgzELiUbvN4oPlgEbdyaWlnbR+3gddoNF63GkE31L4GLkYvR6xltO6Af4
  6ec7001+OPQdeCXGs9db1AkV88+6h2/lTFpvllb1kaoP7gL2XIHTAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRrc6bfOPsRtPDktLmJ+QBuFtDG
  xjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAXSEyKPF936brxSBjOBGjtu7CRL6jMEGs9x+t/brS0L6/
  Q1+auSufw91U5wqGj3sG5HQmeL8Sotfv+4g/ZhH8ZXCAUSEGL5IL/kzTv6yMhb6a
  57J0sex8shoeBiyvNXcBLolv88GPPi9FgX+uzKBl+RFqeLt7Sr+6F16qttfZh0Qn
  71n5hYg2r5/B1gbqbhPJcoWYs5dyiEpTkmqZ+3HIrIpHQDcItiKpnVfh8Caxe2m6
  D+gOhFp0WFVCANwPaPHyuepfG9eoYZVbL2ho+PldZnohgCH4kLmX1mdUr1N/IT0i
  bnj0bCII1eGETpNSHqh8LuH4cJeFVGpKWgbsqGv5+g==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQR8PNgmnnpmypAEBKrfL4gjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzE2MDgyNDU0WhcNMjUw
  MzE2MDgyNDU0WjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuk9Wtmn68F3WKZ8o
  V42v8vLRNWdfMJRwe3a9/5CGerXUgZ7JK/Hzb2YfuUS3z089MZFZvwXbAY9RQeE9
  q5cycNQ17D25uSnJgPddY2kEtOq7EfhoRsyxcBOJvMBSxVmnJBpfwK3DzuyCdzQe
  /Odzx1TB8+3cG4ARa//LIMNifX36jNxcA8zBcCDxu+UHQxnqzDZrnzupCa8uag9Z
  hzdSrqJEIh/wrVL09ZDoK4rPKPIfXZmN1P5c/B00w7GxKTq3NCDuUaTGwqak3hsM
  ppc7PtIh/vJj3cT0rypJSfdTpfPhRG7olGVGf1BDGUBUdIKuOFdakRTJ1LoUpT2k
  VN7wKwIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUa3Om3zj7EbTw
  5LS5ifkAbhbQxsYwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  AIiWetjFWhlzggEbo7g6DD3nadGoUrXkXnsYd2gtouXGuqxW9bWfKkhHcYrxzxfP
  l97qPJdc7ppubZ8rTWcy7DjspWu/2nwFMEFI2jHssIo9X24TdbnaydYn8nhvQHrG
  UCt2Hqbp9E6SdZTPTad8wSGNULsR8VQ+xwh6zfDJLifKUiqZUP8U5NUZn/4vrd3w
  UU314haqSm+INfQSaPk+GuMT6f/8L+sRX3OJszzEooFPt4v+cAJ3N9lAxs+ZhFjM
  2lcTM065hhtZwwm7oi3ABiW8weI22Yb+nTalOUXvH7qjhasABjLTD0fdsGNrVMMA
  CrMWOQtomIKCdT0BhFm+c2Y=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAuk9Wtmn68F3WKZ8oV42v8vLRNWdfMJRwe3a9/5CGerXUgZ7J
  K/Hzb2YfuUS3z089MZFZvwXbAY9RQeE9q5cycNQ17D25uSnJgPddY2kEtOq7Efho
  RsyxcBOJvMBSxVmnJBpfwK3DzuyCdzQe/Odzx1TB8+3cG4ARa//LIMNifX36jNxc
  A8zBcCDxu+UHQxnqzDZrnzupCa8uag9ZhzdSrqJEIh/wrVL09ZDoK4rPKPIfXZmN
  1P5c/B00w7GxKTq3NCDuUaTGwqak3hsMppc7PtIh/vJj3cT0rypJSfdTpfPhRG7o
  lGVGf1BDGUBUdIKuOFdakRTJ1LoUpT2kVN7wKwIDAQABAoIBAEvuhfK2YtWQCPbR
  rQlx76HeoLFZPgx4kxden7UG3Cgq7z8czfShGYvvXUKO5TMSomgPSzp1UnriREXL
  XO0QJDij5I4x4f27MCrlpiQb6xUpDbEXQriIOFDrRZmt8I4KKfqm3RuUNlehQNMA
  ZRjB5Af7XUjjSm/S1Ebl642g1AU8ncUGz5LQvwrMbkr8W6lY2M0LNb9XZEztRGwL
  y5D5ZyDSMMEd834Xhfawe+9kg/AZpyNjBOTcdiXhxaeeRz/9HtSMds+rR9lCd1lu
  B9N0b2d9X6C0WdeHWbt6ozrE+PHqG0DeaE8iuDbfGlLlSUuK+8xO+pNz5zzuV9T3
  PaNfQhECgYEA89pXSygHE1De6Zc4lzYb4LWxGCFVm5eyon3nLyw0yf8ljQmqFtRL
  9Z3VKIRYs9w3sFhfP+YyJrfG8a+KdnEEBuFSvsAGbRvxQz2ipEEDGw4ZpGBtPO75
  vZODuwOGhEdIaPUa9s5raXTd3bPenQIpHCueeSJHPoqYvosG5qTYN98CgYEAw5cy
  2Et3TNNL/Tj8f/HOWIwQaGFsBuy/exlMJitYyvM3nZakYxiofpVgSb8nCJDbt9U6
  OZ1unrb3qw5xClDQNEj1mmVCzeydQte4jczWtcjlDC1d2ceBYkmYRKc9zfFb44zc
  +KPiSr+A0ZqswsR8WV/K5A4IsUscofXNSY6MgTUCgYEAkFis17ZICe0TJt73Brtm
  4StsO0ZwMHwpp/ozQT8/uFqqVcRkxMLCfBADv8on37/5zw9gwqh3A2hCAYrRwa7A
  nXn/yx5ML4Yc2JrBjc1WE0vTbfQOdcVYXBnYHnnFxMOVX1vHrFUgS/p74uK4YeSH
  hT9kvXvHBIRySkhtu1XVD60CgYEAkkUZlh3hywddlbKvSjOYYCnm/1iUBB27GSET
  DJxwG96F4glNSHqhT4EAcEZOt541YqZIk9vDZVhpoXf8W32SJvfFDMDbk8p21Q0k
  jI76pxnlCRVIUVxcyxdEk1sK4l+0m1i1zBArZEEQ4i+tMT7ly6TSw3gnUgddE1YS
  Pwcm1l0CgYBDbc+JEIxegu/NVSCYppijHrUn0Ue596oysTr+GucZp5YDmvPg+sOR
  SYd3LuyLfbDn9rERJiGjUZ1FDlcGEpxqHnKKfhX1+1lBIIhwQKeivJu4viuIsC8t
  b3E3EVMxT3nSqVBQNlFyAi4xoiOB6Xmc6aiFsTpOqKXZACE4RmImZg==
  -----END RSA PRIVATE KEY-----
api_connection_string: localhost:8001
name: admin
