ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAKv655A4PrMYZMADZofkeb0wDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDIyNzA0MjY1MVoXDTM0
  MDIyNDA0MjY1MVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA67qY2g/BRDUyZvuQSHLyeOM9GgTJyTc5
  tMkZb2Vaf11/6CGVU4GYNYdxXmH9uTKU3Ldk9MrIAEIMFOKl1v2g02Xwc4xkK8NN
  d/IV9RhaZ8JmEY5wi0HWkboJ92ks+lG+gJ/Vq43KKbJOjUx1ygnqL40xMxy0Fakg
  rniEQfP7IVzHzwZUOz78v9iAUL5Tb4JWXf3dMJvSKHDUdL8FYHFGPZSlfU3EC2qB
  mFSOtaOmD4US6/5iH2w8hnEaYMakRa9Vr8mEYt/LTQK9gXpYrGsYKPk+Dcznxecx
  Sxm1c4gWqcCj4qIKGMVz64aVxS9YZFkVeQaM61zVzubx8TMLRlzzowIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUjW81wnBSZq1+4vSB6+VrpFTk
  DJkwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAI5btPb224/hVhwUUBZ6izzYKa3pHGiCp0M1WmGi/30i
  5Fkyi15NWtgoaOxUgHyNnVvKBn2inHf5LkNHHis4uYJZPL8b0zuOGtgVGnpoiYn5
  ZjfcQ8Wyvcsyd7virvoj60/BfKffltkFzUMUNwX1o3TfvfkhO7ZYcwVJF1sVZ89+
  /LdLhbr/AiCXzCCpymWhWcQrI7wTxoCO2kFuubCIksUhFy46yHhcjq+/GZtqHq18
  p14Eij9sRVBcR9osuOkGyb/1XxmEGUkk4dI689UOlvvvrbAC5frUTa16a06D1UmS
  0UnMuwVQG+lDNL5mJq2OMF4oWzBNGweqUEHfc1YS6gE=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQScF8BNoUbXxw39RZyP8jujANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMjI3MDQzNjQ3WhcNMjUw
  MjI2MDQzNjQ3WjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3MM7lWtDV2oBjZM7
  MJE4fMQCNkhHdt/uE8Zf4+GXsIvf3lPEhLsed/ZrS+P22zbH+s0mh700i89SyPR2
  LwwmiazSQ0biB5ixH3EYzanZRAzLN73luY0dWsgZi+AEKCvWrYKHwP1fCcTaXNfJ
  RQ1vjZ626r0sxQ65YcmPfX20R2Bazt1QXe3skUdJtRh+8dadEGSU/SSsyZempjFT
  CK+0LDT+Zyc7r8a9OroFiDf0N8eZw5jDmEIC4SeOh85edNrekfJ7bwVTANs0gMXC
  hCN6UWN8TXLIe7pj9W/BhSmvbjMllvX7xprSaNyEhCqF2bfFz0MODPswTiVRIInp
  pcR8AwIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUjW81wnBSZq1+
  4vSB6+VrpFTkDJkwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  AN/oALyhzut1MKwFSGFtzuFVd6A1giohEW0QnCGKupLTCFO+0fuMU4dRBK/WIuZp
  knovAT9TFZk5Ev6+bAT0D61AeAoRlvEaJHdC0R7vKZSmF/lv0Yy1m2M0jp5qOGop
  6mlSpRuFn/CB1CBjYbwYHiYrH514ETqtYH8iXuO9Z9PlNRSoyebL1H6/UrgFh7hD
  zMfEaJCfLXxe6EAvWbn5PEXo0jYfUgFSnJ5Ls7ElgqSS3dpNkpBTdGhRsku7/GDk
  8RyP1Mtj8uBxzXhXqYD3qH/e7+I4rd6kHC3U55/7odYkx0INxRe8A0tvm5dUM/ar
  19vWT1smeoaoLAqGBjVls7I=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEA3MM7lWtDV2oBjZM7MJE4fMQCNkhHdt/uE8Zf4+GXsIvf3lPE
  hLsed/ZrS+P22zbH+s0mh700i89SyPR2LwwmiazSQ0biB5ixH3EYzanZRAzLN73l
  uY0dWsgZi+AEKCvWrYKHwP1fCcTaXNfJRQ1vjZ626r0sxQ65YcmPfX20R2Bazt1Q
  Xe3skUdJtRh+8dadEGSU/SSsyZempjFTCK+0LDT+Zyc7r8a9OroFiDf0N8eZw5jD
  mEIC4SeOh85edNrekfJ7bwVTANs0gMXChCN6UWN8TXLIe7pj9W/BhSmvbjMllvX7
  xprSaNyEhCqF2bfFz0MODPswTiVRIInppcR8AwIDAQABAoIBAQDB7BnOAmAwTGU6
  2QdYfWiSaJfM2Sc1rDV1V3/qLMPUCLrJkOoC8mAsXuEX1BOHsxJuJIHhIPokiiUd
  c2jRoSnFLHOzN3Pb2mxUw0NXfgjldxuYRo6itOwBT97o+QqNwxycZBoeFDPE4BA1
  GDSsHMZOMApcH3tRSsLbvHP4d1DClKYvVZOaGxQaUQsvghMTflqJ25+zf13McUJx
  7/iaQC2GAl5HewHgbMyANrq30v7PzhWaVXZmnqjHBFcJCrikehKz0Ib1APtYQiX6
  5qkZaT6kpNOe5RKad2LSStJ32xOlAD+O86oO8s6pJsii5BEuUymCTzL6CR9CZw3V
  RQKzM21pAoGBAOAtkNWyBZo9QpAAqgDE4Ayd8xa5/AeHWDE8b5GK0g7lqVjmEvLf
  IQQIMsGohgNCKqMes0P5aWCiNlv1M7QfdHeuh3cRWI3+qmEwCnA1BJ+UxNy02dJD
  hRfhGDYbWf5evBVwDAl8xMFHHSqNqaJaVl3YUYJtRG9Mejbq9VFCfZ+vAoGBAPwZ
  jj5mhmEKgLALOCnLW4r7HuCbqfQtexvpJeRKqDDw5l6eK07+hJcicXHek2ShpyGt
  w1/qB1UrlsnlmLk3XglfMdqd3F3xcRXsoEjlEP0scTF/gV+hI+ilKMYYYN2GJIyu
  LB2G2O/WqkLRjTOedBaIM2bcX2z1fdUgUP147YntAoGBANumKbQH8o9WmKJp1Che
  vjv+gtDwt+1UgmfzlElhYEHyaoRNIaHQWBQQSFMRYQVOTmJ3USQ3+zUQmvxs+xTw
  gPhHDDnwx/iQ3rXNEV0xxW7qoBy0InxvZbeo+EUDdaDTh6vllhWxp0LM/9nS5bPK
  mbbnna2SjCwVHeYzPtw4rsfHAoGBAPeBw6TCFda6cAPmz/pAnJzD1dnhGqgP6xlI
  +xm6rox2R0bH9W819UlI2KZaRs165FLtfa7yXsag6AdKsnnNwTZkTtb7O7rD7CoB
  SpCmzNozwuI88/DGjTHAzVpH3vo+1C2GZuuKU/yM/lZh1EbEn+brS8QGQm4AS81u
  T/W7v0M1AoGAIU0JVUbfwYlOFxcMrxy8yTo9D2nwdEPlG061ou6L6LuCpERXfZY9
  TaVXy5YR3xhkeBVwAP6Ch0IAQhlrv51+UReP94tmA5wh4TODI4VsaOEWclJPhftU
  bRnbjsgD3bL6PGFInEVMucifS6q1bTrDhTrVlEXbxz2NQo9Bi25KfCQ=
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8001
name: admin
