ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAJ02Ei0pY+fBAnCe7j6AtkYwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDIyMDA0MTIyMloXDTM0
  MDIxNzA0MTIyMlowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArCQWwfOporEE8ACZluV60nzhc/2qtoqE
  BPVCprqLTpIYQC9Il/XSe7aahad7HnYtiyrszT7wnwpXgpknYxJ8drLq55iKk0BL
  Gz35lv6QthLBIQ7nlrcgquaBeWet/o7bP0yVllh9Fd72Axc93HrkOXFZMzH6jETZ
  M0Zd+3gV7xT2Z3F6zZ0uZhyN+kB5ADX02EEcyz4jKpBS7gb9Zz5uFdPoxd0l5jm4
  Oz1cYnhxsh6iTxRsgbDJYaTaKYxWY//UKmAnS+Rv69VjcpQz0ZecrdyyAdz20Ifa
  TrzDouvYkiL9LKZnIVZObIlGWD28cfAw3BYIjYAcLwmfzOOqA9HTpwIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUW9w+QLEbXoshf7kee4fnCKYc
  u0UwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAEniTdojORy4RePCfMQwii2DdE3GnJuGSJsKfzMJsoCF
  6vBx10QEf2TwzHOUgNXS+RGLUou3M8Ubjdxod3GvYkB7BJ8QYbJ6nt30z2jwf6ke
  Ljc24iezucyziRImwTiwc0Tx8XpQTPWW9/H4IplToFp1dAyT7l8SMG0x9hmWhlEX
  FevqJVjQoIRbXfO6S8d4/zQoj7cVAeuwS/qe9yS9yce7pa1KheSSo+DUtVom0pV0
  uQyjpM/wVIlIo2ZygRN12pQBs8AHHUzEf4XFuJNu62bjaJZ+UGTHLRd8ik+cP6Th
  0wOE7goPtK+iTmF137WR6GEXMy9LK96gSqFR+JRmgn4=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPjCCAiagAwIBAgIRANMOzrzOJ4YjcjX8WAGzhuMwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDIyMDE1MTg1NVoXDTI1
  MDIxOTE1MTg1NVowJzEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMQ4wDAYDVQQDEwVh
  ZG1pbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJp7J3UfdYroM+eI
  RdwGJkTRGULg93SvevoTgwYX38N7onaEtb+l0R5o2QChuWNn0VZNRcYI6aUvPhTX
  asBsjLQ+jrc4DXaSSZ/L3+x8dvZL9FuGdNOEhWwGkYFLo7wr7tcRSRSmxbkneTN5
  DNOWqnSo71cU25Fv7h8TaJ0jmdVsi235xbpnjwENxxTluMBlV5fNmJ9N9JwJ503s
  zh82t6lSyAVFhxYs0fEWBR2Y2wBOiwNeEMpvXQpKY39IP6prxkzYvIeIi8s+BmZ3
  ymotS1UVJtf1lIps17/7FK/fR67FIFkBiPZQbRZBASwwMmWNXJ/OCFvoSxVvLYMA
  3rqwVWkCAwEAAaNyMHAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
  BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFFvcPkCxG16L
  IX+5HnuH5wimHLtFMBAGA1UdEQQJMAeCBWFkbWluMA0GCSqGSIb3DQEBCwUAA4IB
  AQA6oGRVR1qeuZDbgpEGSVtz0b2SCRmsMNlRso3E370M1RE7g2t14Nkx9X3SNjYV
  WeZUpjiq2STWdph6VggA0g2eSNPbgMnDTvuKogsC1OrZgtHNULyukgO+IybKaRvL
  ubIMSoceaKGJtTRUveklc3hESOePH7+ltkRM6iF/j2a+URxcALwdMnBEvgy4ZbnB
  a4dMb1BtkkgpOLXKzRhZIYOsStQ9gX04SxLEQEdqhvd7dxegzhqbSnHK/pawRwcU
  LV5jLZsvvAyb/F5dPDdxydRzB8+TICKAA227jDuRO2WFsDB7QlVk7we5zAGtCSul
  xrbzO3JyzcyyyvQt3SqD5979
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAmnsndR91iugz54hF3AYmRNEZQuD3dK96+hODBhffw3uidoS1
  v6XRHmjZAKG5Y2fRVk1FxgjppS8+FNdqwGyMtD6OtzgNdpJJn8vf7Hx29kv0W4Z0
  04SFbAaRgUujvCvu1xFJFKbFuSd5M3kM05aqdKjvVxTbkW/uHxNonSOZ1WyLbfnF
  umePAQ3HFOW4wGVXl82Yn030nAnnTezOHza3qVLIBUWHFizR8RYFHZjbAE6LA14Q
  ym9dCkpjf0g/qmvGTNi8h4iLyz4GZnfKai1LVRUm1/WUimzXv/sUr99HrsUgWQGI
  9lBtFkEBLDAyZY1cn84IW+hLFW8tgwDeurBVaQIDAQABAoIBAFEoyJcY+wkKa1KF
  3qX0uSBIdqwTQw6Trtk5bQnDezTZfIYlvNK+C/qc/Pz++kYGYg2kNTcQsaeuBUCv
  2A7WOKntf880bKZRvspsMu2sildlmjCHmFMT+YDChqlWEuSmdCmblDh8Ub6vxVZM
  j3eOXWlC49NtStnC42iCKuD7tjNQrYDhfVjUScTRPHnXfTRIPQx4RWu2mBAEqXqR
  y/te2ybVosOEoUxPTAeAPhAhYFDBBYm81UmzfscxRlBrAvV+9PdYZKM5b6VE2WIV
  Qq972UtBN9SIR/dlbUT3N9PiX3/K94jp7AoHVOfZcUEko4VioWjRwlx5qtfp6tFd
  BdFh+gECgYEAy31HFvVaNGFnFC5esfTYGN8YgMCsOFmEGmsFRMAt1qrTOmiTSjxz
  TfKvqh3R7F2CkFVuqlEx3bCXoMspCUgvjBAC9ANUmB4CGBqxj6CrpYUjLD55DmOz
  Y6T1tihRPrnmuUaZOaYSCttW9iQB+K+VeZ/1kHegz3cw6XrqRIN1eakCgYEAwlhW
  M9Wc7CifJHyi2yM3Z1O8THk5OJQgJouTkTbN4mqjBZl9H025PtNx5AEJrJ5AXA88
  gLGEwKInTYzRNv1ZI68+ok9ab+2Hmd7I899aue5Z6hSaurhiO/Hi07jEQ6IxmYFn
  UFjpCx5SzcEjbpye53yku68LE8gkYs27HIV21cECgYAFoq+QVDUuVDA9n9chiI1f
  ivYrwqpCWUBOVv5rXAMo+cwlxvWlTa1H0FvLE05YBHL0Oll5QAxoflaErnuxdR1T
  /LGIPnteRx55umuGdcWrLNe/hu9lVZ+HN+9SHyW43f8kzG676PyA7ngnEvI3B+3U
  03hCiv2aIUvqe2v3f8iGGQKBgQCMACzhHFH2AfFazHpZGI5x3e14vZ8N9g8PFV9R
  rcQ1BhK4FvD+2vPGoXWbBXBdrIa6irNQFhGG34kmoXmZfnp3bWfWbwm8NcWIf+gN
  XmoyJNUa/orUVb1WZ5K6aJDiE/ZdGc4+ID6JJugJlseaiDMkmTLmjVuSfYxQrNnM
  2wxXQQKBgFoL1tpEJBByJ9p3NlGaY9msvW5h1aJpn1N43MKjwl9fZhAi5oU/vvWa
  +lU7RIJNUyBatzBBIjQfNpJwYKVKOYcocagu/iv0bvBSg8AccS0HP+z6mHWzW6qG
  1qnpQgaveQrJsoFh4xHDQX9g3xV5mRDlX3bMW40v0s1lssFDjNfv
  -----END RSA PRIVATE KEY-----
api_connection_string: localhost:8001
name: admin
