ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQFx2Vd1U8lIILF2QjwVqfHjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzExMTU0ODE0WhcNMzQw
  MzA5MTU0ODE0WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTQfyhhBXHTlQNJgpfsgcjyoRcFDvmQyn1
  53c6+e+XOAxl3bxwluOoMD25FHEWYd4XIGJCbhWOe4jZnYGA7j93+v1r+tsGFNOL
  78tHfwX/iyzuek5Ji1FDdHiu+OqmjATsHcBXq3rLwWtRmckvDh9iLxZqKsZZQq6r
  mf+qQA0oGYgItoGpTJq9MbnrDf0xChZ6tITkBQmzf0vDhGfKKHWadh6VBVN+IMQL
  iUnAIGvQgzELiUbvN4oPlgEbdyaWlnbR+3gddoNF63GkE31L4GLkYvR6xltO6Af4
  6ec7001+OPQdeCXGs9db1AkV88+6h2/lTFpvllb1kaoP7gL2XIHTAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRrc6bfOPsRtPDktLmJ+QBuFtDG
  xjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAXSEyKPF936brxSBjOBGjtu7CRL6jMEGs9x+t/brS0L6/
  Q1+auSufw91U5wqGj3sG5HQmeL8Sotfv+4g/ZhH8ZXCAUSEGL5IL/kzTv6yMhb6a
  57J0sex8shoeBiyvNXcBLolv88GPPi9FgX+uzKBl+RFqeLt7Sr+6F16qttfZh0Qn
  71n5hYg2r5/B1gbqbhPJcoWYs5dyiEpTkmqZ+3HIrIpHQDcItiKpnVfh8Caxe2m6
  D+gOhFp0WFVCANwPaPHyuepfG9eoYZVbL2ho+PldZnohgCH4kLmX1mdUr1N/IT0i
  bnj0bCII1eGETpNSHqh8LuH4cJeFVGpKWgbsqGv5+g==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQLgvdgxrn4tyE2dEwoI/tCTANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzE1MTQwOTUxWhcNMjUw
  MzE1MTQwOTUxWjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAumfWi3MUdg0l19gp
  mlMlVrwwTFPLo/kXdn3wrXFe3lacliARyzJ9vf1UA22LXMs03dO+Zi1fZXbsD2Rf
  V2GW0dsfgsi52xZSvskNgTxWM3R9zZJmGIZW0R6+3xm5yIW7JPsSKaYTA6pRIHAH
  x0Su9b/IQeO7FOu1w1JZ+NUcvmPwTTdlplgxIbDAEyGSoFTRjhrEFSj9BvoBsog/
  J2jGfcy9pHT8lMO+VgjaDJ/6Bw6yT++358K1BvcKZ1oT2eBydTTkUxQcroPYtJ0H
  OI/gzndMNAtBe3wDgyJGv79TLyHopQnpX5zL3WsD2ixQEeeAUTitn9i+ODQ8bBEI
  pz6PbQIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUa3Om3zj7EbTw
  5LS5ifkAbhbQxsYwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  AIPAm7xwFnO3e+i+PuWQmTAsU0H3BHSNTW4kM4u9qO0+mbY6ZvejNMvGgqAtwanA
  MeYy1dbrDSXltV1N2lzecIQdmPoQztfRxEELmVYGEWx/jhFxrD7eVmuDdsLXzgz4
  W7gz87p7AUxVdZC8RbdoNZdTXXOSGtQA9O/MegW+riiuFbyUymXn7sjLjv8o62Be
  N2EFbfL1Ns/P7gnHDhLwePLokG0VTgA7bF0lekm9wqEJ5esd2z2kjmZ3BHxSIdGj
  XyQWJTcD/NbJ+DY8LMtfZUxLDNdw+fJWdenyb1p9t3h90ij6wI2zy7KV/2x2o4qM
  8HVIl93FlbkkGbjPFjaE8So=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAumfWi3MUdg0l19gpmlMlVrwwTFPLo/kXdn3wrXFe3lacliAR
  yzJ9vf1UA22LXMs03dO+Zi1fZXbsD2RfV2GW0dsfgsi52xZSvskNgTxWM3R9zZJm
  GIZW0R6+3xm5yIW7JPsSKaYTA6pRIHAHx0Su9b/IQeO7FOu1w1JZ+NUcvmPwTTdl
  plgxIbDAEyGSoFTRjhrEFSj9BvoBsog/J2jGfcy9pHT8lMO+VgjaDJ/6Bw6yT++3
  58K1BvcKZ1oT2eBydTTkUxQcroPYtJ0HOI/gzndMNAtBe3wDgyJGv79TLyHopQnp
  X5zL3WsD2ixQEeeAUTitn9i+ODQ8bBEIpz6PbQIDAQABAoIBAQCLKMYUaR9XWk1s
  LCYy3eu8KtXrxYr7qRQJE9A/y6lFV2ei8+IUzmbtFVhJDtjBt7qJ+G/mG+1h9Dwa
  6ZX7yBEuLeYCXxPRKYMwhywb1Q2NcGQSuj6aBIB/sfJQ4AXAW4Xw/7b5fNApJldW
  XgyQiQgM0tYPypF59tZFMQ+WIpNI1k/XbFssWSn6ErOeUMhFym9JdaMpJ18j+Q8l
  P38THykNPm67Uce9MURVzOSTKge/6EVQTr1mtfwPZId6j1rgFqA5/bYtKAXipfqa
  X0H30LiSe4lU0E44/HdQrIACOo9u2Gz42jBTmYHSFil2txUcFNyVIYFHLeV2jfHn
  0o0OMNmJAoGBAMjUTQkD3ceeAmD/YOiENV4PLpw2DBnpJClxRCAReuSwg2mUdFkg
  +AC7+tmH5kAbC1GabABDaTksbRq+JMe5TODxB79iwryiaTI9RFo9bZryZl4QTgV0
  AlY4cph0HK2hLbIPkGsN/PKDOxkoK4+fknhCEHB6lo22JrNs/v1AOLunAoGBAO2d
  KhmH4qkfkkvGV62/pFEemYsi5qLdv3nETYGz2h+lizxXE522aM8dPslxJzbp44Q+
  kk6JXTSKF8rPC2OM47odz2Ze2IsYjCUOjYK39PKohskdBdAUBNtiFiNRvmlajTrw
  5joRkgHVCzgZRutF22KnIwPI09MTeX9207uNYG7LAoGAMSyCnFV9BXa0IGoHoYdV
  xe0zvX4iYmnKt/cK9ksxazOpSb3W60f+Ube1iXQUNdgpYlbMYRggeKZfJLAwM1M0
  9tMt0XfuNOAToACObwYhg1IdLKUTZZRtSg1SSfAMYZtYpAPZmcz4Ba2KV/OVDvrE
  k3uhqNjralGSklZ67Sm/ensCgYEA7OgsF3RyOuktdbt1o9hVPkPiFuVfSrcIt6FP
  HahyK+dj4W94MWCzMv0XosTcslWT8EBqoz813LJqclzoIANS8jfSl2CtSlHZOQE/
  ejtrT51TdaUoLIQpK4qqQ+C2llggQ8n34aGvD4CYRQB+wwjNaZj2wkkzWVorYzjY
  dkDJCu0CgYBJlGB+sJSH39xuJTFNnpjNCRVHkL5YO7UW1leJQSyrRzspmVFoAH6M
  kfRCfAdxhzkEB4/5gg0taFGN9QbD5cRbFQW7NLOxQQfgHlGzm727eo8848CAEbVV
  8nFJQ8tQbEE5GHHnwxgUiYFWlgXuC8jTHHj4Jp8Pz3OUSl6VQeRfRw==
  -----END RSA PRIVATE KEY-----
api_connection_string: localhost:8001
name: admin
