ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQFx2Vd1U8lIILF2QjwVqfHjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzExMTU0ODE0WhcNMzQw
  MzA5MTU0ODE0WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTQfyhhBXHTlQNJgpfsgcjyoRcFDvmQyn1
  53c6+e+XOAxl3bxwluOoMD25FHEWYd4XIGJCbhWOe4jZnYGA7j93+v1r+tsGFNOL
  78tHfwX/iyzuek5Ji1FDdHiu+OqmjATsHcBXq3rLwWtRmckvDh9iLxZqKsZZQq6r
  mf+qQA0oGYgItoGpTJq9MbnrDf0xChZ6tITkBQmzf0vDhGfKKHWadh6VBVN+IMQL
  iUnAIGvQgzELiUbvN4oPlgEbdyaWlnbR+3gddoNF63GkE31L4GLkYvR6xltO6Af4
  6ec7001+OPQdeCXGs9db1AkV88+6h2/lTFpvllb1kaoP7gL2XIHTAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRrc6bfOPsRtPDktLmJ+QBuFtDG
  xjAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAXSEyKPF936brxSBjOBGjtu7CRL6jMEGs9x+t/brS0L6/
  Q1+auSufw91U5wqGj3sG5HQmeL8Sotfv+4g/ZhH8ZXCAUSEGL5IL/kzTv6yMhb6a
  57J0sex8shoeBiyvNXcBLolv88GPPi9FgX+uzKBl+RFqeLt7Sr+6F16qttfZh0Qn
  71n5hYg2r5/B1gbqbhPJcoWYs5dyiEpTkmqZ+3HIrIpHQDcItiKpnVfh8Caxe2m6
  D+gOhFp0WFVCANwPaPHyuepfG9eoYZVbL2ho+PldZnohgCH4kLmX1mdUr1N/IT0i
  bnj0bCII1eGETpNSHqh8LuH4cJeFVGpKWgbsqGv5+g==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQAiL6WqE60AQ+uhzPjVLGUjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMzEyMTgyNjIwWhcNMjUw
  MzEyMTgyNjIwWjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo/niMCXPzOzD/Nmz
  aZfxBKdiOzTByUQNFyTxQJKqojfRX5ptl+y69pmXN8cg8Hfp2tPUrylTkq0FsD8V
  HY+7NqXDqmIIgkwtJ7VszvNzkFrbamYjjQVL0AX8Wqp4ZRBy4EM8Clc2FLUjUCE4
  VMUHOK25uSd5nHpxL0wFUo2TnYNaclZdmqHaOJO61x39Qh09XVOilCKco8IJPtDf
  sNfOMqu/QrkxIHIz5nKPktS0drkCOnuPRdwrUuO+l7R6yLJRrp+utBGrF5ryGGHb
  yL1mZlAlqGprJkwzPX/R4xMiZZ9lqUjqHoFaYJwcf5E4z5y5i7UQL9/5u/ItEnz1
  zFiKCwIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUa3Om3zj7EbTw
  5LS5ifkAbhbQxsYwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  AASsl1NJCq/lIkYJeWY5qe1Y3wq9TbLdwU+LDGgJgYDgv9R/kKjP6uI3URptATiz
  8xW7xtud+2OZJMdcNGrLvsaz6AhENFdlsOO8Yae9wHblal2rsN867BldLR7DKU30
  WcVtf89eioxvBpa0gxxlpr42BmrR1qM4hkCrNmMBscSkTd1Mvoi1n4WXnlH9G3NG
  fy6J2XVYeaKCz9WSkxzJ9FSU4u1kXR7wC267xAvxcnbCsVohMD3fTWeyOC3+o7ST
  eKFZMWb97Wt2HHLlwFnn7s7e+sRWwe58MknGG5D5/H6uSPFT3W9f5Xa8yt5zCdUn
  ZViih5SCKAcjB3qzLxJAKaU=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAo/niMCXPzOzD/NmzaZfxBKdiOzTByUQNFyTxQJKqojfRX5pt
  l+y69pmXN8cg8Hfp2tPUrylTkq0FsD8VHY+7NqXDqmIIgkwtJ7VszvNzkFrbamYj
  jQVL0AX8Wqp4ZRBy4EM8Clc2FLUjUCE4VMUHOK25uSd5nHpxL0wFUo2TnYNaclZd
  mqHaOJO61x39Qh09XVOilCKco8IJPtDfsNfOMqu/QrkxIHIz5nKPktS0drkCOnuP
  RdwrUuO+l7R6yLJRrp+utBGrF5ryGGHbyL1mZlAlqGprJkwzPX/R4xMiZZ9lqUjq
  HoFaYJwcf5E4z5y5i7UQL9/5u/ItEnz1zFiKCwIDAQABAoIBADcGW4icp6a0rO/k
  ffgpLI/LO4NyqLTJSTtDAlIQ5YGaCYBzaeNZZUPrNntZLwyCsM7l1rEQxSKrPQVv
  pb5NxR0JcydxzjkrJtv0XZb0ywrd8lM6AyQHavFbkNs76TrA0ku/RB6UNWmtfzQc
  cbLAizPR2EjxnjWMQP8GG6MgLzDjoZN04eihndYPHm/DDT4NtSk48rIwJJcgNP4a
  iM95n1/uzp59QXRbLU7KD8e8Um2X7147XTH4rA7GGrjhCZ2UnYJ1/HDEReGV0ICN
  K8AuBzoZ9b5IU8q3gdPKqLaSFd4reJaG2f3SyLyc/HUcUfwcYRptpsEQ5ppe09OJ
  BqJwQEECgYEA1MIuOdb3jgtf5WfehI2C8ry57qbtOvGoRar5dUFCk3JlvmB7nqmu
  k65oMgP140/SOKWh7arcOQKu8WXucVArelvUWvzpZF0cF+8kOdQdGfPxeurbTcHB
  s1QdkFYu8kyrsmfmQLuPXOrsP0QfKQ+TakeIbxIUaQJbcnYYcjfQIscCgYEAxU2O
  PDEjkFkBriYgrpyioqSInYpG5z7BnrhCPhXIRnd4lkmQXFb0Z2PRBGqwse7QGbCp
  odKev0mRuP+JGrcIttVoWSGXNCDjxnAK7DT0Za6bkoZznm2g+6LWDQN/7xfpeJBE
  wziEldGgrCGMPXgpv943mrSpTJzX2BqdA/V9Gp0CgYBeUuRpkitYVyShsQYO4Cog
  8ZjA/FKKYl7G3EESQeeBNSN0XpQPyIx0PstE+UqHB3lc0dnTY3+U6uKidR1cMT3F
  Vnb0C9JxQ3JUDhqSZL6uJd92Li8h7vewSGd++SaBF4q7YqLLKhwqBqDMf6gM7THe
  2W3cSDiyQXBHc6Hs6V+mOwKBgH2zKHAOumKnYhuqLN4x6qeF/Yeo5f1DjSVqrMFT
  LVI/oTLWUUOTHoiUHkEbG9FwnWIQnDH9tqeV3mInYxkDDWk2UxGeBe/vGE5/aWYN
  Yrs5X+IdCKIhpBNNLeQCm8oeyN7HwxdA9a9ha2TexrMO0EJt96z3dnjZ3+XNJsWz
  6+09AoGBAJwj1COl7iLFL71uQ7RFOlQzHVwP9Aev7kJ8f0R1zML+d9f+edQdBz/F
  JGtQCy5nCMoXJ5Xf3lXWJtvXow0/FT0wuOKGT0EqJN2VoiXPZQpXv7tVugGJA+a+
  icujgTfpDlGf9sIiRvHl+6dXT184VXnLNjwvmvZFgsWnJBN/NvSj
  -----END RSA PRIVATE KEY-----
api_connection_string: localhost:8001
name: admin
