version:
  name: velociraptor
  version: 0.7.1-1
  commit: 2d7d6cfa
  build_time: "2023-12-27T12:02:09Z"
  install_time: 1709008010
  compiler: go1.19.13
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAKv655A4PrMYZMADZofkeb0wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDIyNzA0MjY1MVoXDTM0
    MDIyNDA0MjY1MVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA67qY2g/BRDUyZvuQSHLyeOM9GgTJyTc5
    tMkZb2Vaf11/6CGVU4GYNYdxXmH9uTKU3Ldk9MrIAEIMFOKl1v2g02Xwc4xkK8NN
    d/IV9RhaZ8JmEY5wi0HWkboJ92ks+lG+gJ/Vq43KKbJOjUx1ygnqL40xMxy0Fakg
    rniEQfP7IVzHzwZUOz78v9iAUL5Tb4JWXf3dMJvSKHDUdL8FYHFGPZSlfU3EC2qB
    mFSOtaOmD4US6/5iH2w8hnEaYMakRa9Vr8mEYt/LTQK9gXpYrGsYKPk+Dcznxecx
    Sxm1c4gWqcCj4qIKGMVz64aVxS9YZFkVeQaM61zVzubx8TMLRlzzowIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUjW81wnBSZq1+4vSB6+VrpFTk
    DJkwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAI5btPb224/hVhwUUBZ6izzYKa3pHGiCp0M1WmGi/30i
    5Fkyi15NWtgoaOxUgHyNnVvKBn2inHf5LkNHHis4uYJZPL8b0zuOGtgVGnpoiYn5
    ZjfcQ8Wyvcsyd7virvoj60/BfKffltkFzUMUNwX1o3TfvfkhO7ZYcwVJF1sVZ89+
    /LdLhbr/AiCXzCCpymWhWcQrI7wTxoCO2kFuubCIksUhFy46yHhcjq+/GZtqHq18
    p14Eij9sRVBcR9osuOkGyb/1XxmEGUkk4dI689UOlvvvrbAC5frUTa16a06D1UmS
    0UnMuwVQG+lDNL5mJq2OMF4oWzBNGweqUEHfc1YS6gE=
    -----END CERTIFICATE-----
  nonce: QYw9rEfgKlc=
  writeback_darwin: D:\Download\velociraptor\config\Velociraptor.writeback.%NONCE%.yaml
  writeback_linux: D:\Download\velociraptor\config\Velociraptor.writeback.%NONCE%.yaml
  writeback_windows: D:\Download\velociraptor\config\Velociraptor.writeback.%NONCE%.yaml
  level2_writeback_suffix: .bak
  tempdir_linux: D:\Download\velociraptor\config\temp
  tempdir_windows: D:\Download\velociraptor\config\temp
  tempdir_darwin: D:\Download\velociraptor\config\temp
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.1-1
    commit: 2d7d6cfa
    build_time: "2023-12-27T12:02:09Z"
    install_time: 1709008010
    compiler: go1.19.13
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
API:
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 127.0.0.1
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgIQW6jytEfBrTyEH7OtQjBN/DANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMjI3MDQyNjUxWhcNMjUw
    MjI2MDQyNjUxWjApMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dS
    UENfR1cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8zHGBD+3o+Zw7
    J04fN8sGwfG5Fp90APgkQRbkV2iU6bptHyZplYWEkB38EVi52fX6RZu1hFspyY3o
    53bJnFXEG6QIihGJJJQMsHNXOWniR4dVcHbduFj/+npdMSsGWNj8XmzFnosErHic
    EFRs+3sbcGdsHeUbmMaxYgU3ArIxMJ1sU8nOQp4WEIHmpEV7GjHQQ2Y2vb1VPI0V
    eUkAd4QDRmL/sSikt4EbXTCr2jigvEjFexsO7VSFoneBFn3CjRJW1hufHOMAR6kW
    BLNo0QvpUWRi3PSFVq4CSJSICpXOmeHsOVEnV4xkBvYkWPdTkSd0ThKHxrxRlvHf
    FcwJBGy1AgMBAAGjdDByMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEF
    BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSNbzXCcFJm
    rX7i9IHr5WukVOQMmTASBgNVHREECzAJggdHUlBDX0dXMA0GCSqGSIb3DQEBCwUA
    A4IBAQB/HKjWkFdyUnOC9f1/mYi+7kjXi64XLEH8AvBqGjPGvnUtowJr1kvhFl2h
    21CaLL8UmmWZAmTJq+HBfB1NdCluGcYm8joCERXl/nCPcwR/Kzr4MO/qh4X0L283
    DG7XMGDDsjmHTbZtO6G48PoZFueoEh7HR+wFvAm+X/nHrn7ui/6Hdi5gMYJ7m9Ti
    7ouGhz9hGbUgAUb90ZYzlC0k6drVC5VRfEXhjpTCEqUbBqrkfgJ9cHheCYYnGJRE
    b+G2YTbX9ET/n89cjyBh4XwU9tx785Fc9t9//FMNXlTqcrWWsicVhvJb1+Srn3Zq
    7P99FZ7emfbm6Pk0yJxRAyQpiS3b
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAvMxxgQ/t6PmcOydOHzfLBsHxuRafdAD4JEEW5FdolOm6bR8m
    aZWFhJAd/BFYudn1+kWbtYRbKcmN6Od2yZxVxBukCIoRiSSUDLBzVzlp4keHVXB2
    3bhY//p6XTErBljY/F5sxZ6LBKx4nBBUbPt7G3BnbB3lG5jGsWIFNwKyMTCdbFPJ
    zkKeFhCB5qRFexox0ENmNr29VTyNFXlJAHeEA0Zi/7EopLeBG10wq9o4oLxIxXsb
    Du1UhaJ3gRZ9wo0SVtYbnxzjAEepFgSzaNEL6VFkYtz0hVauAkiUiAqVzpnh7DlR
    J1eMZAb2JFj3U5EndE4Sh8a8UZbx3xXMCQRstQIDAQABAoIBAQColYXk0OyH1BuF
    VpuTlKZd6mCF/YV0eEkbVmOykbp4/hvRxLbwIOuQa3/azUKE8fOK/w0DEKS2s5tc
    FRMlA8wxyNy4I1F1PIxWqFjV0haST3yw9jOt2CbgrDEHdhgNGtjmwQovjFpmWft4
    n7xDdGuBHOW8zRT/h3QkgHpXnLiw4kePVWFyF+f52u2k1wfdV14Vt5VDYWN3tyXP
    3tL3P3ikdDhzgz/zZdrVTMpO1Ja6tFE3yTA1pIDUZNo9mi9zdfWTBcnirR+lWtZ7
    bzD5dllKk2LRIlMdkD+YfK1gDH4DHmD6gF2KO2sTE17djxfwiMCn1YqUauS08oYY
    8QDsQx8hAoGBANz4UfMv5PmWkDEjqudC7oLwC19ulDjbLvwt0fORxWtAyGFr2uXc
    PSqReObQ2hoIX9lj6mxGa3EFgldnQjJg1wIdYpCBDfh+8r0BO63RpCTWzeXjcQNc
    EBTrVp2AOQ2XnIhzLHrAaIhAbKMoMwQBXZxyQnv8GnUyNzwC3xwsjd33AoGBANq6
    gPFJzuHoyxIDhbgAY7KZJqe33BM5FoBANa/6HIWU+bKXY/Jm4cuxgnCUsnkHiCnl
    G1bXiQjfd2C6lY74avTIZc2k1Z3RHPIkphxnywFQ0nU0MQYx1dECza7P2cy9ZG53
    ihcQfOdyzpDI7BO6xKI1ScQ1IzD4bRDWDuM/hU+zAoGBANE1pllKEk+glrp/m5LD
    UxDTduEOz/UYyF5of2xNqo2GU3GxbRnOMHc6Li7StHyLSzyGle+XqKfkYGiiUhFi
    kI7nBWftWC3a+7WpEjja0L80RNMQSPK2Wl+EBYivWtUco06pRQafXxkJbhH3wH1d
    UaUKpRnAMcieF5+Q1G5XXKY3AoGALrYdy2nj0MMSeypdaEpNAFtMsgzF5yUN9R3B
    WW+kn7KNEOLb6WynVAT4wmo/IzHElo3jJMyq60YuDG5Melf7H4OcmipVpHqAIAZL
    o01XQVStXXJj9dq2uwhKPMcO0Hax+BV3XC2dPyB5lNoT8LK2Q531vv1KIq8rO6k7
    TLTIF5kCgYBZ0aBYS/DxFAmFprkJAwxPcF5qHTb0lXylqMePGS0bG+3nZVkETVU6
    8+zyChP/4NEZN56tOhAusOX4onoV01U7oxD9p5VI5Xp0p7mllUzZLVCASSlmgj7R
    IZ45GJINlS8TE2rAm4s9PeoV390lf1+qL6xDft9GxhStrLpkW28vYA==
    -----END RSA PRIVATE KEY-----
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  initial_users:
  - name: admin
    password_hash: fbbb2f8e1c98ace8ebc211e13449ec5a2d1c7c9c41275b679c9bf7bdfb29f422
    password_salt: cb35cf8ef1c13aead6e560027bc9e96a50738d7ed18ff140daaf95071e242c14
  initial_orgs:
  - org_id: O123
    name: ACME Inc
    nonce: ACME
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA67qY2g/BRDUyZvuQSHLyeOM9GgTJyTc5tMkZb2Vaf11/6CGV
    U4GYNYdxXmH9uTKU3Ldk9MrIAEIMFOKl1v2g02Xwc4xkK8NNd/IV9RhaZ8JmEY5w
    i0HWkboJ92ks+lG+gJ/Vq43KKbJOjUx1ygnqL40xMxy0FakgrniEQfP7IVzHzwZU
    Oz78v9iAUL5Tb4JWXf3dMJvSKHDUdL8FYHFGPZSlfU3EC2qBmFSOtaOmD4US6/5i
    H2w8hnEaYMakRa9Vr8mEYt/LTQK9gXpYrGsYKPk+DcznxecxSxm1c4gWqcCj4qIK
    GMVz64aVxS9YZFkVeQaM61zVzubx8TMLRlzzowIDAQABAoIBAQDQZlgJuJIBThJw
    LwjAtDafHy5+mSsX4+X1aTA+ZllabnvM6hvNBq5c7JAShAk+uHQYqV3seHXWnI13
    zWQWLIYJPn8UeFJ6yh/r4a79zvjl8FwyOz5OLveWP+XdwDMOXkRQDH5nO2Q19rgx
    fR5JbviF74pGiKLA35PQCyXJ9PvY4i3qRTcV0SeCoDybAprmWsUSTzJori97MAoW
    OpPqf4EKuqPWl6lESIp7L8aMIvrGxAU0SHz09bnl28S8qn97HXb+zs6BKGbLEJoi
    G4UdQjWbhl48JjE1F0faNcF/xv8TlwRn4EUMsk14M1Q/NSnWnhZGQRISWIjlLcvb
    KX4i3JIhAoGBAP8+xNL4oPf0inOm8Ay0SA/nBMJbC5WbLR/U2WSwo7XFs/R7WE/8
    ntWuRxxBRYwfiQkslLL+4ADoe2XRtopdDik3PtfLw1n/QMXvXkrJH578tNS9yclk
    ldoHoR+SIfTh6urqap7Q4y9MdFzmtcrbYZ7emfTkfe4xMNiEAPaqTM8xAoGBAOxt
    DbgftMNu4q9M8mgBvjQdVuMwXlsl2l5lxh1ez6W/F1KsRRC/ylIOwoHRX5haxA+d
    MqI5KzIbIHgAkBAgxB+CqAiIpCDxieaOfg8GPkWJKR6m4ZlLpKRYcnVYWrunlG+J
    HKA/y+s5qzsSTADClDri8Ul5Vilr0LPdTZxI/AMTAoGBAOBYSGFynPEz5Flguo9A
    CjLICBvYMGdvvArFZ8qjo1EKk3Bo1aeAUA9anjAMgtd1hFom8BAgC71gmc1VtY8J
    2X+KilbcRzkcLM+M5CDxhDSWw05V/j1ghoHbwNfh9qypwXR3U/2Bdp3FImXhdpn1
    l2kvGLzx9GnenKNB6yLjbp2RAoGAFaF0m9/qvearPrafhvyB1mrIxEhsmZJBBFnz
    YkSGYve0vo+cUgf6Dr/i89WgFWRYg8UyGL16Qj9RHSmQBKm6x9dAYGd//LOclkd7
    KQy9Lcd6x58lDM1q5s5gynOm+Xw/jGTTBaZQldjU3bay1W73+NtCkCJVy7xdf9dD
    foT+6ZkCgYBthqeGp/EPQ1EoF4uVm1BR7fRfEJPjXQrOQcFvllcdNO4eBA4hD650
    /iV0Q1ArPV5nFrDCXhYUF2JWbWCQwin/KPromb9J1gSoL25sMk2q8ex0QSkA0K/+
    F/Y+Od801nS2LwUJudjGpWzctJj4KsDgMTwfoOW79hSLxX+907wqzA==
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: localhost
  bind_address: 127.0.0.1
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDVzCCAj+gAwIBAgIQFVyn5nh5XPW0ltVHsXnrWjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwMjI3MDQyNjUxWhcNMjUw
    MjI2MDQyNjUxWjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl
    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    ANVwhuywbZzPBS6X/1+Q8ocV3U5vQpKqku+l4DZQ8QZqnfnir7RmpbRQmb5rX0L0
    ZyZUAVDFinsC4Nm7xXK3tGJ0oOCfJDk4EGsF4r4VJPX2AAoMWwNU7I/w968jsXXj
    by3NvIhHQdCY3IHMURp/JK7YaHDZr2CtxhcQCUIxXuY0K3bnmrYcBOvla9Dayb41
    /I/99zeXjESOVcI/t4xn/FlQf8mkUmms2iWYJVTChZL2oiBuNCBYtjkcISB7pGWJ
    swLaPAm+19GpDseQDTutCk01w/uYoLh4eOwee1lCO3VbzXenbzD0he4ePmN6HIud
    dmn3x3zCfUZerPZYy7XCuVsCAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFI1vNcJwUmatfuL0gevla6RU5AyZMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv
    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEASHXT7V+WA4DUt1mgzmYOtElGnTcA
    cMTG8EkxQGShYzjnoAuY/uNY32Hydd2kZYCg96x/G13e9xWVLL6ZBEi1L9OrFcmC
    dQrhp/ouwSK3hE6lLq5Es5ZsMwY2FeRLK44HmETCA6NMZVGmUSkz5MCi4xkJteL4
    H6qkD4SQT+iox+INFOfKWI/eFRVClu3jPCcx/djpuMVsw8xrG1SDQvPxvuk7TvGt
    YfoacQ63wy4qEF+OhF0fzJAnpFr/u+2nBUwNNFKZKHFrihcHb4fapF0bpA4jCPeF
    Bj7MjfD7C93OEFuux5s4hIAsZHVO6g5YxpafZdwgx+eSGWpH61mSvWF1YQ==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA1XCG7LBtnM8FLpf/X5DyhxXdTm9CkqqS76XgNlDxBmqd+eKv
    tGaltFCZvmtfQvRnJlQBUMWKewLg2bvFcre0YnSg4J8kOTgQawXivhUk9fYACgxb
    A1Tsj/D3ryOxdeNvLc28iEdB0JjcgcxRGn8krthocNmvYK3GFxAJQjFe5jQrduea
    thwE6+Vr0NrJvjX8j/33N5eMRI5Vwj+3jGf8WVB/yaRSaazaJZglVMKFkvaiIG40
    IFi2ORwhIHukZYmzAto8Cb7X0akOx5ANO60KTTXD+5iguHh47B57WUI7dVvNd6dv
    MPSF7h4+Y3oci512affHfMJ9Rl6s9ljLtcK5WwIDAQABAoIBAFsyQ1QqZgtUISCx
    bToGErpJS0/SFh3YqAOhWlWa7AET2QAGLZDlMvQCZE6KTh+rkc88oXtDjFHW/v/J
    TSog+AABWSPgm3efTtSLpUAWhL5bJ9UjRlf8Fz/Bc/LvS0nVrZFikKWh3KsmRUFo
    bVbm8GOMr8NYH6ktVrBP98TCl4vAAtqnfDQzp1CfjIzTc9U/eRb8TMo8SwxnFA0L
    SC+qwvhpmUZF22Vz8QG3ffcjSpFPbwUtJpaPlIqq5LWucr/OSQmKMgotGGYus0/1
    +ZUnVIUQIV6YUHNI4PK8LgV2Ktgd2EBJ+N/MICSDXJfGx+85Oyfnv6O50+45B4vQ
    uWsdXFECgYEA8fXYut/mA4rhMRKy3pH35Fsj3znBLvbe+Q5c/qV+UxNK+o+cT50a
    jVP4o8J52ZcNpG39SQqdNzGMNYfPhpDKvd9Ue2Or9ZE47p+nIWwmyOj/60aRGNpE
    vtvu7rrmIPWp6QnujzTi/IES3T55xfC523y2Cjg52s3DHCuJbjyDdPcCgYEA4dMG
    JRUqXNXF2cJFGDNvRsp6k/kliuFP6dIUTGAX14EJ1qFKkbdiywCuvW3G1kCID/Uk
    G487EyGH/ZU+GGXzhH14cgEL7jKyQ9KenhLEIgMF0+RHeuPEQ089BJqqI3lOrYBC
    sTJrPZzq5XCq/URysgvR7zBe8wghqmH2+eXw2b0CgYAsOd6qkcBOR3VP7fYJ3q5r
    7AjLhZf9CJzK80gmN4O2laEv2U4d8z5mNMIO1L5G+mhA9OXGEw2XiBPzuOZC13Zn
    bEnZ3+cPlMLOQxpebpFMSeJ1U8mzvDmylSrAMiNcROsQsIMNZAJVWxZioEfL2Wtv
    ZgU0KwDQMKoIHSEaqC7zEwKBgQCkgrWkSCH/VWB3/bWWJso22QSpTcSSwwcTgI53
    AT39Ka0AJaoMM3uOBaZGq3VB2esFLQGr7hEMI85M5u9AmOzpJPqcmrSVR2tkS0hw
    QZ2OZYNWVKPaG5l7q3r5Iq81fobZkGmFawSC8xCQKx71uGqR2FiMlkFlbRQRaqKg
    dGmcRQKBgQCE+W5k975LHjxxperipKvw02gvebb8lIx0txng7ZVDUkDgxWnc5Qso
    eBjIpa9M/3e4a9h954cubLQJ546aWDnh0HuSeytdXRPIzKwzu8YM/7RW4RKkLMyb
    GIV+ElCY9ooeA7icPz0+6u7r1QkqmgCF2nkBamUCqil+N3FNGp8HWw==
    -----END RSA PRIVATE KEY-----
  do_not_compress_artifacts: true
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: D:\Download\velociraptor\config
  filestore_directory: D:\Download\velociraptor\config
Logging:
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
obfuscation_nonce: CY2c/EK+HYA=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
  event_max_wait: 1
  event_max_wait_jitter: 1
  event_change_notify_all_clients: true
